# Generated by Django 3.0.3 on 2020-03-19 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.TextField(default='', max_length=20)),
                ('Content', models.CharField(default='', max_length=20)),
                ('Author', models.CharField(default='', max_length=20)),
                ('Date', models.DateField(blank=True)),
            ],
        ),
    ]
