# Generated by Django 3.0.3 on 2020-05-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Content',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
