# Generated by Django 3.0.3 on 2020-03-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Number',
            field=models.IntegerField(default=0, max_length=20),
        ),
    ]
